language: scala
scala:
  - 2.12.8

jdk:
  - openjdk8


script:
  - sbt clean coverage test coverageReport
  - sbt ++$TRAVIS_SCALA_VERSION test

after_success:
  - bash <(curl -s https://codecov.io/bash)

