language: scala

sudo: false

# These directories are cached to S3 at the end of the build
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/scala-$TRAVIS_SCALA_VERSION

scala:
  - 2.12.7
  - 2.12.8

jdk:
  - openjdk8

script:
  - sbt ++$TRAVIS_SCALA_VERSION test

